# Ques: Use the digits datasets from sklearn and make a KNN classifier

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [4]:
print(digits.keys())

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [6]:
df = pd.DataFrame(digits['data'])

In [7]:
print(df)

       0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0

       56   57   58    59    60    61   62   63
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0
...   ...  ...  ...   ...   ...   ...  ...  ...
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0

[1797 rows x 64 columns]

In [9]:
df["target"] = digits['target']

In [10]:
print(df)

        0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0

       57   58    59    60    61   62   63  target
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0       0
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0       1
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0       2
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0       3
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0       4
...   ...  ...   ...   ...   ...  ...  ...     ...
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0       9
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0       0
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0       8
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0       9
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0       8

[1797 rows x 65 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(df.drop("target",axis = 1),df["target"],test_size=0.3)

In [21]:
print(x_train)

       0    1     2     3     4     5    6    7    8    9   ...    54   55  \
1229  0.0  0.0   7.0   5.0  14.0  13.0  0.0  0.0  0.0  0.0  ...   0.0  0.0
712   0.0  0.0   1.0  10.0   0.0   0.0  0.0  0.0  0.0  0.0  ...  15.0  2.0
1532  0.0  0.0  15.0  14.0  15.0   9.0  0.0  0.0  0.0  0.0  ...   1.0  0.0
95    0.0  0.0   0.0  11.0  16.0   8.0  0.0  0.0  0.0  0.0  ...   0.0  0.0
1058  0.0  0.0   9.0  13.0   6.0   0.0  0.0  0.0  0.0  0.0  ...   6.0  0.0
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...   ...  ...
789   0.0  1.0  12.0  16.0  13.0   2.0  0.0  0.0  0.0  5.0  ...   7.0  0.0
48    0.0  0.0   2.0  15.0  13.0   3.0  0.0  0.0  0.0  0.0  ...   5.0  0.0
82    0.0  0.0   0.0  10.0  15.0   3.0  0.0  0.0  0.0  0.0  ...  14.0  2.0
94    0.0  0.0   3.0  12.0  16.0  10.0  0.0  0.0  0.0  2.0  ...   0.0  0.0
839   0.0  0.0   8.0  16.0  16.0  16.0  3.0  0.0  0.0  0.0  ...   2.0  0.0

       56   57    58    59    60    61    62   63
1229  0.0  0.0   6.0  15.0   6.0   0.0   0.0  0.0
712   0.0  0.0   2.0  12.0  16.0  12.0   6.0  0.0
1532  0.0  1.0  10.0  16.0  15.0   4.0   0.0  0.0
95    0.0  0.0   0.0  12.0  16.0  15.0   0.0  0.0
1058  0.0  0.0  10.0  14.0  14.0   7.0   0.0  0.0
...   ...  ...   ...   ...   ...   ...   ...  ...
789   0.0  0.0  16.0  16.0  15.0   8.0   1.0  0.0
48    0.0  0.0   4.0  12.0  15.0   6.0   0.0  0.0
82    0.0  0.0   1.0   9.0  15.0  16.0  11.0  0.0
94    0.0  0.0   5.0  13.0   0.0   0.0   0.0  0.0
839   0.0  0.0   6.0  16.0  16.0  11.0   0.0  0.0

[1257 rows x 64 columns]

In [23]:
print(y_train)

1229    0
712     6
1532    5
95      6
1058    9
       ..
789     3
48      0
82      6
94      7
839     3
Name: target, Length: 1257, dtype: int32

In [24]:
print(x_test)

       0    1    2     3     4     5     6    7    8     9   ...    54   55  \
948   0.0  0.0  7.0  16.0  14.0  13.0  10.0  0.0  0.0   0.0  ...   0.0  0.0
769   0.0  0.0  4.0  15.0   7.0   0.0   0.0  0.0  0.0   1.0  ...   0.0  0.0
555   0.0  0.0  2.0  10.0  14.0  10.0   0.0  0.0  0.0   1.0  ...   9.0  0.0
1233  0.0  2.0  9.0  16.0  13.0  13.0   2.0  0.0  0.0  11.0  ...   0.0  0.0
518   0.0  0.0  2.0  13.0  11.0   0.0   0.0  0.0  0.0   0.0  ...   4.0  1.0
...   ...  ...  ...   ...   ...   ...   ...  ...  ...   ...  ...   ...  ...
802   0.0  0.0  0.0  11.0  13.0   5.0   0.0  0.0  0.0   0.0  ...   4.0  0.0
528   0.0  0.0  5.0  16.0  14.0   2.0   0.0  0.0  0.0   1.0  ...  10.0  0.0
1766  0.0  0.0  8.0  12.0  11.0   6.0   0.0  0.0  0.0   0.0  ...   0.0  0.0
909   0.0  0.0  0.0   4.0  15.0   2.0   0.0  0.0  0.0   0.0  ...   0.0  0.0
1462  0.0  0.0  0.0   0.0   3.0  14.0   3.0  0.0  0.0   0.0  ...   4.0  0.0

       56   57    58    59    60    61    62   63
948   0.0  0.0   9.0  13.0   0.0   0.0   0.0  0.0
769   0.0  0.0   2.0   9.0  12.0   3.0   0.0  0.0
555   0.0  0.0   1.0  10.0  15.0  16.0   6.0  0.0
1233  0.0  0.0  13.0  14.0   3.0   0.0   0.0  0.0
518   0.0  0.0   1.0  15.0  16.0  16.0  16.0  7.0
...   ...  ...   ...   ...   ...   ...   ...  ...
802   0.0  0.0   1.0  10.0  16.0  11.0   1.0  0.0
528   0.0  0.0   6.0  16.0  14.0  12.0   9.0  0.0
1766  0.0  0.0   4.0  11.0  12.0   7.0   0.0  0.0
909   0.0  0.0   0.0   4.0  16.0   9.0   0.0  0.0
1462  0.0  0.0   0.0   0.0   5.0  16.0   4.0  0.0

[540 rows x 64 columns]

In [25]:
print(y_test)

948     7
769     8
555     9
1233    8
518     2
       ..
802     6
528     2
1766    1
909     4
1462    1
Name: target, Length: 540, dtype: int32

In [38]:
clf = KNeighborsClassifier(n_neighbors=4)

In [39]:
clf.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [40]:
print(clf.predict(x_test))

[7 8 9 8 2 6 5 4 2 5 2 5 9 9 0 2 3 0 6 6 5 2 3 3 5 2 2 2 3 4 9 0 1 0 7 1 2
 9 7 8 8 5 1 8 1 5 5 5 9 5 5 1 9 3 8 9 2 8 0 5 6 0 4 7 5 3 3 8 7 6 6 9 2 9
 2 3 7 4 9 0 7 7 8 8 5 0 7 5 4 5 3 0 9 8 0 8 6 8 9 8 5 7 4 8 0 8 1 4 0 9 5
 2 1 1 3 5 6 0 1 4 9 1 6 0 4 5 8 3 8 9 7 3 9 9 2 0 1 1 9 7 6 5 9 2 7 9 9 0
 7 3 9 1 9 7 2 4 9 1 7 3 1 9 4 8 5 1 7 4 4 0 3 3 3 8 4 2 5 5 0 4 4 3 8 1 1
 6 6 7 5 2 9 2 6 3 5 7 4 8 6 9 1 1 3 8 7 5 6 3 1 3 7 3 7 1 7 2 2 6 6 8 2 1
 0 7 0 1 2 6 6 4 3 0 4 9 1 9 6 5 6 2 0 4 4 8 5 7 2 0 7 4 6 5 4 5 4 0 0 3 4
 3 1 5 8 3 2 4 0 9 8 7 0 0 5 3 5 0 9 6 1 9 0 5 3 1 6 3 8 7 2 0 5 2 9 7 1 0
 6 1 3 8 2 1 9 2 3 6 7 0 5 7 0 6 2 5 7 5 5 4 0 8 8 0 3 8 8 6 5 0 8 3 5 1 3
 0 6 9 4 4 3 7 5 9 0 6 9 5 0 9 8 1 2 6 6 9 9 9 9 8 6 0 5 3 3 8 7 0 9 3 7 8
 7 5 4 7 2 8 9 9 4 5 3 0 1 3 4 8 9 1 6 5 2 1 4 9 3 6 6 4 3 6 6 5 5 8 1 7 5
 7 0 8 1 9 2 1 7 0 4 2 6 8 3 5 3 6 3 6 0 2 4 0 4 7 9 2 8 7 0 3 0 8 2 2 4 2
 6 2 3 5 4 9 4 1 7 6 8 9 1 3 8 3 7 4 9 1 4 7 4 0 1 6 5 6 9 5 2 6 4 4 8 1 4
 7 5 1 2 1 2 9 9 0 3 2 8 2 5 6 2 0 1 6 9 1 1 7 7 4 2 5 0 0 3 7 8 5 6 8 7 7
 2 3 8 4 0 7 7 5 4 3 9 7 9 1 3 2 1 6 2 1 4 1]

In [41]:
print(clf.score(x_test,y_test))

0.9888888888888889